import React from 'react'
import './teamprofile.css'
import IDEAL from '../../assets/ideal_table.png'

const TeamProfile = () => {
  return (
    <section id='teamprofile'>
      <div className='teamprofile'>
        <div className="teamprofile-content">
            <h1>Team Profile</h1>
            <h5>Comparison of our Personality Tests and Ideal Jobs.</h5>
            <div className='teamprofile-body'>
              <h3>Personal Profile</h3>
              <p>Damian's personal profile indicates that he is less prone to negative thoughts and impulses and is skilled at controlling and directing his impulses. He is also good at getting along with others and is open to seeing their points of view. Damian's learning style test showed that he is a visual learner, and the Myers-Briggs test classified him as an ESFJ-A (Consul). Consuls are known for their practical and caring nature and their ability to create and maintain a secure and friendly environment. Damian may struggle with finding or keeping a partner, learning to relax or improvise, reaching career goals, or managing his workload and may benefit from putting in a conscious effort to develop these weaker traits and additional skills.</p><br></br>
              <p>Sam B's personal profile reveals that he is an INTP-T according to the Myers-Briggs test. This means he is introverted, intuitive, thinking, prospecting, and turbulent and prefers learning through physical activity. He is also imaginative, open-minded, and flexible with improvising and adapting, and focuses on effectiveness in his thinking. However, he is self-conscious and anxious and is more comfortable around people he trusts. The results of a learning style test showed that Sam B is a visual learner, and the Big Five personality test indicated that he has high scores in Neuroticism, Openness to Experience, Agreeableness, and Conscientiousness, but a low score in Extraversion. This suggests that Sam B may prefer to work independently or in small groups and may need time to process information before contributing to group discussions. He may be a creative and analytical thinker but may struggle with social situations and may benefit from working on trust and extraversion. He may be skilled in organization and collaboration.</p><br></br>
              <p>Sarah's personal profile indicates that she is an ISFJ (Defender) according to the Myers-Briggs test. This means she is hard working, devoted, loyal, has a can-do, caring personality, and is sensitive. She is reserved but has people skills and is meticulous with high standards and high expectations. Sarah is reliable and supportive but may take things personally and struggle with change. She may not feel comfortable standing up for herself or addressing matters where others are not pulling their weight. Sarah's learning style is visual, and she prefers to learn by seeing text and graphics and graphs and likes to highlight important points. She may benefit from taking notes and typing them up afterwards. A personality test showed that Sarah is practical, focuses on relevant matters, and is determined to achieve goals.</p><br></br>
              <p>Sam K's personal profile reveals that he is an INFJ (Advocate) according to the Myers-Briggs test, which means he is introverted, intuitive, feeling, judging, and turbulent. His learning style is visual, with 30% auditory, 45% visual, and 25% tactile preferences. The Big Five personality test showed that Sam K has high scores in Openness, Conscientiousness, Agreeableness, and Neuroticism, but a low score in Extraversion. This suggests that Sam K may be introverted and emotional and may prefer to work independently or in small groups. He may be intuitive and have strong feelings and may struggle with social situations. He may prefer visual aids for learning and may be cautious and driven to improve.</p><br></br>
              <p>Ally's personal profile indicates that she is an ENFJ-T according to the Myers-Briggs test. This means she is enthusiastic, creative, sociable, and a free spirit. She is highly intuitive and emotional and likes to help make others feel happy and successful. Ally thrives under good leadership and works well in teams but does not prefer to work alone. She may be judgmental and may come across as condescending at times but is also overly compassionate. Ally's learning style is multimodal, which means she likes learning through listening, discussing, talking, questioning, practical exercises, experiences, examples, case studies, trial and error, and things that are real. She may be a good communicator and able to adapt to new situations.</p><br></br>
              <p>Brodie's personal profile shows that he is a Campaigner ENFP-T according to the Myers-Briggs test, which means he is enthusiastic, creative, sociable, and a free spirit. He is an intuitive and emotional person who likes to help make others feel happy and successful. Brodie thrives under good leadership and works well in teams but does not prefer to work alone. His learning style is multimodal, which means he likes learning through listening, discussing, talking, questioning, practical exercises, experiences, examples, case studies, trial and error, and things that are real. He may be skilled in thinking outside the box and following directions.</p><br></br>
              <p>This information may be helpful to the group in a few different ways. Understanding each person's personality type and learning style can help the group understand how each member may approach tasks and problem-solving. For example, if there are members of the group who are more intuitive or who prefer to learn through hands-on experiences, they may be more open to trying new approaches and methods and may be more interested in experimenting and exploring different options. On the other hand, if there are members who are more practical or who prefer to learn through structured, logical explanations, they may be more comfortable with following established procedures and systems and may be more focused on efficiency and effectiveness.</p><br></br>
              <p>Understanding each person's strengths and weaknesses can also be helpful for the group. For example, if there are members who are particularly skilled at organization and planning, they may be able to take on roles that involve coordinating tasks and schedules. If there are members who are more creative and open-minded, they may be able to contribute new ideas and approaches to problem-solving. On the other hand, if there are members who struggle with social situations or who may feel overwhelmed by change, the group can work to support them and help them develop strategies for coping with these challenges.</p><br></br>
              <p>Overall, this information can help the group work more effectively and efficiently as a team. By understanding each other's strengths and weaknesses, the group can identify areas where they can support one another and work together to achieve common goals. By understanding each person's personality type and learning style, the group can communicate and collaborate more effectively, and can tailor their approach to tasks and problem-solving to suit the needs and preferences of each member.</p>
            </div>
            <div className='teamprofile-body'>
              <h3>Ideal Jobs</h3>
              <p>Damian's ideal job is that of a Cyber Security Analyst, which involves developing, implementing, and reporting on the organization's information security systems and ensuring compliance with IT functions that protect the organization's assets. This position requires experience in the information security sector and strong communication skills, as well as the ability to think quickly and show initiative under pressure.</p><br></br>
              <p>Sam B's ideal job is that of a Full Stack Developer, which involves designing and building web applications using a range of frontend and backend languages. This position requires proficiency in modern JavaScript and experience with coding, testing, and automation techniques using the language, as well as knowledge of libraries such as TypeScript, React, and Node.js.</p><br></br>
              <p>Sarah's ideal job is that of an IT Project Manager in the healthcare industry, which involves managing the end-to-end delivery of specific solutions to the business. This position requires a successful project management background in healthcare, experience with HL7, Rhapsody, or FHIR, and strong communication and stakeholder management skills.</p><br></br>
              <p>Sam K's ideal job is that of a Business Improvement Specialist, which involves analyzing business processes and recommending improvements to internal working practices. This position requires experience in business analysis, the ability to work with subject matter experts to create working requirements for system development, and strong communication and collaboration skills.</p><br></br>
              <p>Ally's ideal job is that of a Business/Systems Analyst (Information & Communication Technology), which involves managing the software asset lifecycle, including acquisition, compliance, maintenance, and decommissioning. This position requires excellent communication skills, advanced skills in Excel, and experience interpreting licensing terms and conditions.</p><br></br>
              <p>Brodie's ideal job is that of a Senior .NET Developer, which involves building web applications using the .NET framework and the C# programming language. This position requires strong coding skills in C# and at least 5 years of experience in a similar role and environment.</p>
              <img src={IDEAL}></img>
              <p>In terms of common elements, all of these positions involve some form of analysis or problem-solving, strong communication skills, and the ability to work as part of a team. However, there are also many differences among the positions, such as the specific industries and technologies they focus on, the specific responsibilities and tasks involved, and the required levels of experience and qualifications. Despite these differences, all of the ideal jobs mentioned are important parts of software development and contribute to the creation of functional, user-friendly, and cost- effective software that meets the needs of the business or organization.</p><br></br>
              <p>In terms of career plans, while each team member has their own specific goals and interests within the industry, they are all looking to further their careers in the field of software development. This suggests that there is some level of similarity in their career plans, although each individual is pursuing a different role that aligns with their own goals and interests.</p><br></br>
              <p>Overall, all of the ideal jobs mentioned by each team member are relevant to software development in different ways. The Cyber Security Analyst helps to ensure the security and compliance of the organization's IT systems, while the Full Stack Developer designs and builds web applications. The IT Project Manager manages the delivery of specific solutions to the business, and the Business Improvement Specialist helps to improve internal working practices. The Business/Systems Analyst manages the lifecycle of software assets, and the Senior .NET Developer builds web applications using the .NET framework and C# programming language. Each of these professions plays a vital role in the software development process and helps to create functional, user-friendly, and cost-effective software that meets the needs of the team and/or organization.</p>
            </div>
        </div>
      </div>
    </section>
  )
}

export default TeamProfile